spring:
  datasource:
    url: jdbc:mysql://localhost:3306/assignment
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:assignment_jaehun}
    password: ${MYSQL_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
