server:
  forward-headers-strategy: framework

spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/assignment}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:}
    password: ${MYSQL_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

app:
  security:
    jwt:
      secret: ${JWT_SECRET:assignment-security-practice-jwt-secret-key-2026}
      access-token-expires-in-seconds: ${JWT_ACCESS_TOKEN_EXPIRES_IN_SECONDS:1800}
      refresh-token-expires-in-seconds: ${JWT_REFRESH_TOKEN_EXPIRES_IN_SECONDS:1209600}
  oauth:
    kakao:
      user-info-uri: ${KAKAO_USER_INFO_URI:https://kapi.kakao.com/v2/user/me}
    google:
      user-info-uri: ${GOOGLE_USER_INFO_URI:https://www.googleapis.com/oauth2/v3/userinfo}
